### ISSUE TITLE
test epic bad ac

### ISSUE THREAD

**Issue by Sparhawk96** [CS-471-Team-2/CS-471_Fake_Repo#51]
Reference: #100

# Accepriteria
- [ ] Given that, when you, then die
- [ ] Given that, when you, then die
- [ ] Given that, when you, then die
- [ ] Given that, when you, then die
